### ISSUE TITLE
Model using robot future node error

### ISSUE THREAD

**Issue by j2k0618** [StanfordASL/Trajectron-plus-plus#17]
Hi.
Thanks for your nice work.
I got the following error after running the NuScenes Qualitative code with robot model.
Did I miss something?

```Python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-9-1e8bcb6ee3bf> in <module>
      8                                    timestep,
      9                                    ph,
---> 10                                    num_samples=500)
     11 
     12     predictions_mm = eval_stg.predict(scene,

/media/mnt1/Trajectron-plus-plus/trajectron/model/trajectron.py in predict(self, scene, timesteps, ph, num_samples, min_future_timesteps, min_history_timesteps, z_mode, gmm_mode, full_dist, all_z_sep)
    183                                         gmm_mode=gmm_mode,
    184                                         full_dist=full_dist,
--> 185                                         all_z_sep=all_z_sep)
    186 
    187             predictions_np = predictions.cpu().detach().numpy()

/media/mnt1/Trajectron-plus-plus/trajectron/model/mgcvae.py in predict(self, inputs, inputs_st, first_history_indices, neighbors, neighbors_edge_value, robot, map, prediction_horizon, num_samples, z_mode, gmm_mode, full_dist, all_z_sep)
   1111                                                                    neighbors_edge_value=neighbors_edge_value,
   1112                                                                    robot=robot,
-> 1113                                                                    map=map)
   1114 
   1115         self.latent.p_dist = self.p_z_x(mode, x)

/media/mnt1/Trajectron-plus-plus/trajectron/model/mgcvae.py in obtain_encoded_tensors(self, mode, inputs, inputs_st, labels, labels_st, first_history_indices, neighbors, neighbors_edge_value, robot, map)
    491 
    492         if self.hyperparams['incl_robot_node']:
--> 493             robot_future_encoder = self.encode_robot_future(mode, x_r_t, y_r)
    494             x_concat_list.append(robot_future_encoder)
    495 

/media/mnt1/Trajectron-plus-plus/trajectron/model/mgcvae.py in encode_robot_future(self, mode, robot_present, robot_future)
    702         initial_state = (initial_h, initial_c)
    703 
--> 704         _, state = self.node_modules['robot_future_encoder'](robot_future, initial_state)
    705         state = unpack_RNN_state(state)
    706         state = F.dropout(state,

~/anaconda3/envs/trajectron++/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/anaconda3/envs/trajectron++/lib/python3.6/site-packages/torch/nn/modules/rnn.py in forward(self, input, hx)
    557         if batch_sizes is None:
    558             result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
--> 559                               self.dropout, self.training, self.bidirectional, self.batch_first)
    560         else:
    561             result = _VF.lstm(input, batch_sizes, hx, self._flat_weights, self.bias,

RuntimeError: stack expects a non-empty TensorList
```

**Comment by tinmodeHuang** [comment]
hey guy!
did you come across  the case that the following error pops up in that script when running up to the cell "Prediction including Map Encoding".
```
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-120-c36cd443b374> in <module>
     51     ax.get_legend().remove()
     52     fig.show()
---> 53     fig.savefig('plots/qual_nuScenes_map_pos.pdf', dpi=300, bbox_inches='tight')

~/.conda/envs/trajectron++/lib/python3.7/site-packages/matplotlib/figure.py in savefig(self, fname, **kwargs)
   2033             self.set_frameon(frameon)
   2034 
-> 2035         self.canvas.print_figure(fname, **kwargs)
   2036 
   2037         if frameon:

~/.conda/envs/trajectron++/lib/python3.7/site-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, **kwargs)
   2261                 orientation=orientation,
   2262                 bbox_inches_restore=_bbox_inches_restore,
-> 2263                 **kwargs)
   2264         finally:
   2265             if bbox_inches and restore_bbox:

~/.conda/envs/trajectron++/lib/python3.7/site-packages/matplotlib/backends/backend_pdf.py in print_pdf(self, filename, **kwargs)
   2576             file = filename._file
   2577         else:
-> 2578             file = PdfFile(filename, metadata=kwargs.pop("metadata", None))
   2579         try:
   2580             file.newPage(width, height)

~/.conda/envs/trajectron++/lib/python3.7/site-packages/matplotlib/backends/backend_pdf.py in __init__(self, filename, metadata)
    436         self.original_file_like = None
    437         self.tell_base = 0
--> 438         fh, opened = cbook.to_filehandle(filename, "wb", return_opened=True)
    439         if not opened:
    440             try:

~/.conda/envs/trajectron++/lib/python3.7/site-packages/matplotlib/cbook/__init__.py in to_filehandle(fname, flag, return_opened, encoding)
    607             fh = bz2.BZ2File(fname, flag)
    608         else:
--> 609             fh = io.open(fname, flag, encoding=encoding)
    610         opened = True
    611     elif hasattr(fname, 'seek'):

FileNotFoundError: [Errno 2] No such file or directory: 'plots/qual_nuScenes_map_pos.pdf'
```
and link of the resulting figure is here (https://github.com/tinmodeHuang/autonomous-driving-resource/blob/master/qual_nuScenes_map_pos.pdf)
for solve it, one cell having the following  was put before that cell.
```
if not os.path.exists('plots'):
    os.makedirs('plots')
```
otherwise there weren't any predicted trajectories in the resulting figure, note that  nuScenes "mini" dataset was used here

**Comment by j2k0618** [comment]
Hello,
I also got the error when I just start training with the command for +Dynamics Integration, Maps, Robot Future:

python train.py --eval_every 1 --vis_every 1 --conf ../experiments/nuScenes/models/robot/config.json --train_data_dict nuScenes_train_full.pkl --eval_data_dict nuScenes_val_full.pkl --offline_scene_graph yes --preprocess_workers 10 --batch_size 256 --log_dir ../experiments/nuScenes/models --train_epochs 20 --node_freq_mult_train --log_tag _robot --incl_robot_node --map_encoding

Did I miss something?
Thank you!

```Python
Created Training Model.
Created Evaluation Model.
Epoch 1, VEHICLE L: -2.85: 100%|████████████████| 69/69 [00:35<00:00,  1.97it/s]
Traceback (most recent call last):
  File "train.py", line 433, in <module>
    main()
  File "train.py", line 291, in main
    full_dist=False)
  File "/home/vilab/jegyeong/Trajectron-plus-plus/trajectron/model/trajectron.py", line 185, in predict
    all_z_sep=all_z_sep)
  File "/home/vilab/jegyeong/Trajectron-plus-plus/trajectron/model/mgcvae.py", line 1127, in predict
    map=map)
  File "/home/vilab/jegyeong/Trajectron-plus-plus/trajectron/model/mgcvae.py", line 495, in obtain_encoded_tensors
    robot_future_encoder = self.encode_robot_future(mode, x_r_t, y_r)
  File "/home/vilab/jegyeong/Trajectron-plus-plus/trajectron/model/mgcvae.py", line 709, in encode_robot_future
    _, state = self.node_modules['robot_future_encoder'](robot_future, initial_state)
  File "/home/vilab/anaconda3/envs/trajectron++/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vilab/anaconda3/envs/trajectron++/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 559, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: stack expects a non-empty TensorList
```

**Comment by j2k0618** [comment]
@BorisIvanovic Thanks for your answering! I just use --incl_robot_node arguments for training.
And this is my training parameters.
```Python
-----------------------
| TRAINING PARAMETERS |
-----------------------
| batch_size: 256
| device: cuda:0
| eval_device: cpu
| Offline Scene Graph Calculation: yes
| EE state_combine_method: sum
| EIE scheme: attention
| dynamic_edges: yes
| robot node: True
| edge_addition_filter: [0.25, 0.5, 0.75, 1.0]
| edge_removal_filter: [1.0, 0.0]
| MHL: 1
| PH: 6
-----------------------
```
I think I set the value of hyperparams['incl_robot_node'] true but I still got the error.
Did I miss something important?
Thank you!

**Comment by os1a** [comment]
I also got the same error during training with robot_node enabled.
In praticular the error happens after it finishes training the first epoch and during the visualization part.

File "train.py", line 433, in <module>
    main()
  File "train.py", line 291, in main
    full_dist=False)
  File "/misc/lmbraid21/makansio/Trajectron-plus-plus_orig/trajectron/model/trajectron.py", line 185, in predict
    all_z_sep=all_z_sep)
  File "/misc/lmbraid21/makansio/Trajectron-plus-plus_orig/trajectron/model/mgcvae.py", line 1127, in predict
    map=map)
  File "/misc/lmbraid21/makansio/Trajectron-plus-plus_orig/trajectron/model/mgcvae.py", line 495, in obtain_encoded_tensors
    robot_future_encoder = self.encode_robot_future(mode, x_r_t, y_r)
  File "/misc/lmbraid21/makansio/Trajectron-plus-plus_orig/trajectron/model/mgcvae.py", line 709, in encode_robot_future
    _, state = self.node_modules['robot_future_encoder'](robot_future, initial_state)
  File "/misc/lmbraid21/makansio/Trajectron-plus-plus/trajectron++3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/misc/lmbraid21/makansio/Trajectron-plus-plus/trajectron++3.6/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 570, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: stack expects a non-empty TensorList

**Comment by os1a** [comment]
Problem is solved @j2k0618 @BorisIvanovic @tinmodeHuang 

You need to add the argument 
min_future_timesteps=ph
to the call of the predict function at line 285 in train.py

Probably the same applies when calling the NuScenes Qualitative code.

**Comment by j2k0618** [comment]
@os1a   Thank you for your help! It works now! I'll close the issue now.

**Comment by BorisIvanovic** [comment]
Thank you very much @os1a for the fix! I haven't had much time to work on these so I really appreciate any help :)
