### ISSUE TITLE
'MultiPolygon' object is not iterable

### ISSUE THREAD

**Issue by moooises** [StanfordASL/Trajectron-plus-plus#76]
Hello,
I have been trying to setup the nuScenes mini, but using the v1.3 of the map expansión I end up with a **'MultiPolygon' object is not iterable** error when running **python process_data.py --data=./v1.0-mini --version="v1.0-mini" --output_path=../processed**
I know the repository suggest v1.1, however at the beggining I had an "arcline_path_3" error and this [issue](https://github.com/StanfordASL/Trajectron-plus-plus/issues/20) said it is fixed with v1.2 of the map expasion. Using the v1.2 I had error telling me I was using an outdated versión, so I changed to v1.3 .

This is the error login

```
Traceback (most recent call last):
  File "process_data.py", line 472, in <module>
    process_data(args.data, args.version, args.output_path, args.val_split)
  File "process_data.py", line 432, in process_data
    scene = process_scene(ns_scene, env, nusc, data_path)
  File "process_data.py", line 267, in process_scene
    map_mask = (nusc_map.get_map_mask(patch_box, patch_angle, layer_names, canvas_size) * 255.0).astype(
  File "/usr/local/lib/python3.8/site-packages/nuscenes/map_expansion/map_api.py", line 392, in get_map_mask
    return self.explorer.get_map_mask(patch_box, patch_angle, layer_names=layer_names, canvas_size=canvas_size)
  File "/usr/local/lib/python3.8/site-packages/nuscenes/map_expansion/map_api.py", line 870, in get_map_mask
    map_mask = self.map_geom_to_mask(map_geom, local_box, canvas_size)
  File "/usr/local/lib/python3.8/site-packages/nuscenes/map_expansion/map_api.py", line 819, in map_geom_to_mask
    layer_mask = self._layer_geom_to_mask(layer_name, layer_geom, local_box, canvas_size)
  File "/usr/local/lib/python3.8/site-packages/nuscenes/map_expansion/map_api.py", line 1803, in _layer_geom_to_mask
    return self._polygon_geom_to_mask(layer_geom, local_box, layer_name, canvas_size)
  File "/usr/local/lib/python3.8/site-packages/nuscenes/map_expansion/map_api.py", line 1890, in _polygon_geom_to_mask
    map_mask = self.mask_for_polygons(new_polygon, map_mask)
  File "/usr/local/lib/python3.8/site-packages/nuscenes/map_expansion/map_api.py", line 1823, in mask_for_polygons
    exteriors = [int_coords(poly.exterior.coords) for poly in polygons]
TypeError: 'MultiPolygon' object is not iterable
```
And this my project structure. I have been using  Google colab.
![image](https://user-images.githubusercontent.com/19190820/214828513-bd53c7df-d2cc-48aa-a644-c41b5087be78.png)

**Comment by MichaelHopwood** [comment]
Try this:
https://github.com/nutonomy/nuscenes-devkit/issues/852
