### ISSUE TITLE
nuScenes Dataset

### ISSUE THREAD

**Issue by bharath5673** [StanfordASL/Trajectron-plus-plus#94]
trying for nuscense dataset but ending with this :(( please help :(
```
cd experiments/nuScenes

# For the mini nuScenes dataset, use the following
python process_data.py --data=./v1.0-mini --version="v1.0-mini" --output_path=../processed

# For the full nuScenes dataset, use the following
python process_data.py --data=./v1.0 --version="v1.0-trainval" --output_path=../processed
```
`python process_data.py --data=./v1.0-mini --version="v1.0-mini" --output_path=../processed`
Traceback (most recent call last):
  File "/home/bharath/Downloads/test_codes/trajectory_forecasting/Trajectron-plus-plus-Main/experiments/nuScenes/process_data.py", line 472, in <module>
    process_data(args.data, args.version, args.output_path, args.val_split)
  File "/home/bharath/Downloads/test_codes/trajectory_forecasting/Trajectron-plus-plus-Main/experiments/nuScenes/process_data.py", line 402, in process_data
    nusc = NuScenes(version=version, dataroot=data_path, verbose=True)
  File "/home/bharath/Downloads/test_codes/trajectory_forecasting/Trajectron-plus-plus-Main/experiments/nuScenes/./devkit/python-sdk/nuscenes/nuscenes.py", line 54, in __init__
    assert osp.exists(self.table_root), 'Database version not found: {}'.format(self.table_root)
AssertionError: Database version not found: ./v1.0-mini/v1.0-mini

` python process_data.py --data=./v1.0 --version="v1.0-trainval" --output_path=../processed`
Traceback (most recent call last):
  File "/home/bharath/Downloads/test_codes/trajectory_forecasting/Trajectron-plus-plus-Main/experiments/nuScenes/process_data.py", line 472, in <module>
    process_data(args.data, args.version, args.output_path, args.val_split)
  File "/home/bharath/Downloads/test_codes/trajectory_forecasting/Trajectron-plus-plus-Main/experiments/nuScenes/process_data.py", line 402, in process_data
    nusc = NuScenes(version=version, dataroot=data_path, verbose=True)
  File "/home/bharath/Downloads/test_codes/trajectory_forecasting/Trajectron-plus-plus-Main/experiments/nuScenes/./devkit/python-sdk/nuscenes/nuscenes.py", line 54, in __init__
    assert osp.exists(self.table_root), 'Database version not found: {}'.format(self.table_root)
AssertionError: Database version not found: ./v1.0/v1.0-trainval

**Comment by shikharvashistha** [comment]
check this path `AssertionError: Database version not found: ./v1.0-mini/v1.0-mini` and see if it's correct

**Comment by Hongtai-Yuan** [comment]
For this, u can change nuscenes_dataset.py,maybe 304-305,
`    data_path = data_path / version
    save_path = save_path / version
`
change it to 
`    data_path = data_path
    save_path = save_path
`
